name: 'notion-blog-action-tcyun'
description: |
  将 notion database 中的 page 转换为 markdown 文档，可以用于 hexo、hugo 等静态博客构建
  支持自动将图片迁移到 tcyun oss
inputs:
  notion_secret:  # id of input
    description: notion app token，建议最好放到 Action Secret 中
    required: true
  database_id:
    required: true
    description: |
      notion 中的数据库 id
      - 假设你的数据库页面链接是 `https://www.notion.so/you-name/0f3d856498ca4db3b457c5b4eeaxxxxx`
      - 那么 `database_id=0f3d856498ca4db3b457c5b4eeaxxxxx`
  status_name:
    description: notion database 状态字段的字段名，支持自定义
    default: "status"
  status_published:
    description: notion database 文章已发布状态的字段值
    default: "已发布"
  status_unpublish:
    description: |
      notion database 文章待发布状态的字段值
      触发 action 后会自动拉去所有该状态的文章，成功导出之后会把这篇文章的状态修改为上面设置的已发布状态
    default: "待发布"
  migrate_image:
    description: |
      是否迁移图片到 tcyun oss
      注意: 如果不迁移图片默认导出图片链接是 notion 的自带链接，有访问时效
      目前支持迁移图片到 tcyun oss 中
    default: "true"
  page_output_dir:
    required: false
    description: page类型页面的输出文件夹
    default: "source/"
  post_output_dir:
    required: false
    description: post类型页面的输出文件夹
    default: "source/_posts/notion"
  secretId:
    description: tcyun secretId
    required: true
  secretKey:
    description: tcyun secretKey
    required: true
  bucket:
    description: tcyun bucket
    required: true
  appId:
    description: tcyun appId
    required: true
  area:
    description: "tcyun area: oss-cn-hangzhou"
    required: true
    default: oss-cn-hangzhou
  path:
    description: "file dir, e.g. image/"
    default: ""
  version:
    description: "tcyun cos version"
    default: "v5"
  customUrl:
    description: "tcyun cos customUrl"
    default: ""

runs:
  using: 'node16'
  main: 'dist/index.js'
