name: 'notion blog'
description: '将 notion database 中的 page 转换为 markdown 文档，可以用于 hexo、hugo 等静态博客构建'
inputs:
  token:  # id of input
    description: 'notion api sdk 所需要的 token，用于获取数据'
    required: true
  token_v2:
    description: "notion cookie 中的个人 token，用于导出文档"
    required: true
  space_id:
    required: true
  database_id:
    required: true
  output:
    default: "./tmp/"
    required: false
runs:
  using: 'node16'
  main: 'index.js'