name: Build a release for new tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Ubuntu and node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: |
          npm install
          npm i -g @vercel/ncc
      - name: Build ncc
        run: |
          rm dist -rf
          npm run build
      - name: Commit & Push
        uses: action-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'output'
          force-push: 'true'
          commit-message: 'Generate dist files'
          name: github-actions[bot]
          email: github-actions[bot]@noreply.github.com
